workflows:
  android-release:
    name: Android CI/CD Workflow
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
      groups:
        - KEYSTORE_CREDENTIALS
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build AAB (for Play Store)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
