workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - KEYSTORE_CREDENTIALS
      vars:
        PACKAGE_NAME: "com.example.GymTracker"

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Decode Keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/keystore.jks

      - name: Set up Google Play authentication
        script: |
          echo "$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS" > /tmp/google-credentials.json

      - name: Configure signing properties
        script: |
          cat <<EOF > android/key.properties
          storePassword=${KEYSTORE_PASSWORD}
          keyPassword=${KEY_PASSWORD}
          keyAlias=${KEY_ALIAS}
          storeFile=android/app/keystore.jks
          EOF

      - name: Verify Keystore
        script: |
          keytool -list -keystore android/app/keystore.jks -storepass $KEYSTORE_PASSWORD -v

      - name: Run tests
        script: flutter test

      - name: Build Signed APK
        script: flutter build apk --release

      - name: Build Signed AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        in_app_update_priority: 3
        submit_as_draft: false
