name: app
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

# Application version
version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3  # Corrected

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png  # Ensure this path is correct

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Ensure the image exists

